#!/bin/bash

if [[ $EUID -ne 0 ]]; then
    exec sudo "$0" "$@"
fi

if command -v nala >/dev/null 2>&1; then
    nala update
    sleep 1
    nala upgrade
else
    apt update
    sleep 1
    apt upgrade -y
fi

flatpak update

