#!/bin/bash
# Split the current window vertically
tmux split-window -h

# Run 'vim .' on the left pane
tmux select-pane -L
tmux send-keys "vim ." C-m

# Run 'ls' on the right pane
tmux select-pane -R
tmux send-keys "ls" C-m

