#!/bin/bash
#

if [ -z "$TMUX" ]; then
  session_name=$(basename "$PWD")
  if tmux has-session -t "$session_name" 2>/dev/null; then
    tmux attach-session -t "$session_name"
    exit 0
  else
    tmux new-session -d -s "$session_name"
    tmux send-keys -t "$session_name" "$0" C-m
    tmux attach-session -t "$session_name"
    exit 0
  fi
fi


# Split the current window vertically
tmux split-window -h
tmux resize-pane -x40% -L

# Run 'vim .' on the left pane
tmux select-pane -L
tmux send-keys "vim ." C-m

# Run 'ls' on the right pane
tmux select-pane -R
tmux send-keys "ls" C-m


